backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true


# publish mode
publish_mode: editorial_workflow

# medial library
media_folder: "uploads"

# collections
collections:
# Main Categories
  - label: "Main Categories"
    name: "main_categories"
    folder: "_main.categories"
    create: true
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Category Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Enter the Category title."
      - label: "Brief Description about the main category"
        name: "body"
        widget: "markdown"
        required: true
# topics
  - label: "Topics"
    name: "topics"
    folder: "_topics"
    create: true
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Topic Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Enter the topic title."
      - label: "Main Category"
        name: "main_category"
        widget: "relation"
        collection: "main_categories"
        search_fields: [title]
        display_fields: [title]
        value_field: "title"
        required: true
        hint: "Select the the main category where the topic belongs."
      - label: "Brief Description about the topic"
        name: "body"
        widget: "markdown"
        required: false
# Authors 
  - label: "Authors"
    name: "authors"
    folder: "_authors"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Identifying Name"
        name: "name"
        widget: "string"
        required: true
        hint: "Use a code or name which is used to identify otherthan name.)"
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        required: true
        hint: "Your Fullname."
      - label: "Your profile color"
        name: "auth_color"
        widget: "color"
        required: true
        hint: "Choose a color to use in your profile page for elements like buttons etc."
      - label: "Avatar"
        name: "avatar"
        widget: "image"
        required: false
        hint: "Your Profile picture"
      - label: "Show my profile photo"
        name: "show_my_photo"
        widget: "select"
        required: true
        options:
          - { label: "Yes, Sure!", value: "yes" }
          - { label: "No, I don't like it!", value: "no" }
      - label: "Gender"
        name: "gender"
        widget: "select"
        required: true
        options:
          - { label: "Male", value: "male" }
          - { label: "Female", value: "female" }
      - label: "E-mail"
        name: "email"
        widget: "string"
        required: false
        hint: "Ex: john@example.com"
      - label: "Website"
        name: "web"
        widget: "string"
        required: false
        hint: "Ex: johdoe.me"
      - label: "Facebook Username"
        name: "facebook"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "Instagram Username"
        name: "instagram"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "Whatsapp Number"
        name: "whatsapp"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "Twitter Username"
        name: "twitter"
        widget: "string"
        required: false
        hint: "Ex: john_doe"
      - label: "GitHub Username"
        name: "github"
        widget: "string"
        required: false
        hint: "Ex: johndoe4"
      - label: "About You"
        name: "body"
        widget: "markdown"
        required: false
# podcasts
  - label: "Podcasts"
    name: "podcasts"
    folder: "_podcasts"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    delete: true
    editor:
      preview: false
      delete: true
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Title of the podcasts. It must be catchy and brief."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: [display_name]
        display_fields: [display_name]
        value_field: "name"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Related Topic"
        name: "topic"
        widget: "relation"
        collection: "topics"
        search_fields: [title]
        display_fields: [title]
        value_field: "title"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Upload a image related to the podcast."
      - label: "Audio file"
        name: "podcast"
        widget: "file"
        required: true
        hint: "Upload you podcast. File size below 10mb"    
      - label: "Description about podcast"
        name: "body"
        widget: "markdown"
        required: false
# videos
  - label: "Videos"
    name: "videos"
    folder: "_videos"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    delete: true
    editor:
      preview: false
      delete: true
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Title of the video. It must be catchy and brief."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: [display_name]
        display_fields: [display_name]
        value_field: "name"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Related Topic"
        name: "topic"
        widget: "relation"
        collection: "topics"
        search_fields: [title]
        display_fields: [title]
        value_field: "title"
        required: true
        hint: "Select the author from the dropdown list."
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Upload a image related to the podcast."
      - label: "Video Platform"
        name: "video_platform"
        widget: "select"
        options:
          - { label: "Youtube", value: "youtube" }
          - { label: "Dailymotion", value: "dailymotion" }
      - label: "Video link"
        name: "video"
        widget: "string"
        required: true
        hint: "Enter your video link."    
      - label: "Description about podcast"
        name: "body"
        widget: "markdown"
        required: false
# articles
  - label: "Articles"
    name: "articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Post Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: My First Awesome Post!"
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Upload a image related to the post."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: [display_name]
        displayFields: [display_name]
        valueField: "name"
        required: true
        hint: "Select the author of the post."
      - label: "Topic"
        name: "topic"
        widget: "relation"
        collection: "topics"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: true
        hint: "Select a topic related to this article."
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Tags help to get indexed by search engines."
      - label: "Small Description"
        name: "description"
        widget: "text"
        required: false
        hint: "This text is used by search engines."
      - label: "Article body"
        name: "body"
        widget: "markdown"